# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-09 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='http://127.0.0.1:8000/'),
        ),
    ]
