# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-20 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161220_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default=False, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
